#CS375 Project 2
#Austin Willis
all: count-opens lsl kitten

count-opens: opens.cpp
	clang++ -std=c++11 -o count-opens opens.cpp

lsl: lslong.cpp
	clang++ -std=c++11 -o lsl lslong.cpp

kitten: k.cpp
	clang++ -std=c++11 -o kitten k.cpp

clean:
	rm *o lsl kitten count-opens
